Projeto_final/cliente/urls.py
from django.urls import path
from . import views

app_name="cliente"

urlpatterns =[
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),

    
]

Projeto_final/lojinha/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('produto.urls')),
    path('cliente/', include('cliente.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
   
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#TODO: remover debug toolbar
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ]+ urlpatterns

Projeto_final/pedido/urls.py
from django.urls import path
from . import views

app_name ='pedido'

urlpatterns =[
    path('', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('detalhe/', views.Detalhe.as_view(), name='detalhe'),   

    
]

Projeto_final/produto/urls.py
from django.urls import path
from . import views
from produto.views import cadastro, adicionarproduto, conexao, detalheproduto, edit, update, delete, estoque
from django.conf import settings
from django.conf.urls.static import static


app_name= 'produto'

urlpatterns =[
    path('', views.ListaProdutos.as_view(), name='lista'),
    path('<slug>', views.DetalheProdutos.as_view(), name='detalhe'),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(), name='adicionaraocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(), name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name='resumodacompra'),
    path('cadastro/', cadastro,name='cadastro'),
    path('adicionarproduto/', adicionarproduto, name='adicionarproduto'),
    path('detalheproduto/<int:pk>/',detalheproduto,name='detalheproduto'),
    path('conexao/', conexao,name='conexao'),
    path('estoque/<int:pk>/', estoque,name='estoque'),
    path('edit/<int:pk>/',edit,name='edit'),
    path('update/<int:pk>/',update,name='update'),
    path('delete/<int:pk>/',delete,name='delete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Senha/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Projeto_final/cliente/views.py
from django.shortcuts import render, get_list_or_404, redirect
from django.views.generic import ListView
from django.views   import View
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
import copy
from django.contrib import messages
from . import models
from . import forms



class BaseCliente(View):
    template_name = 'perfil/criar.html'

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)

        self.carrinho = copy.deepcopy(self.request.session.get('carrinho',{}))#copiando carrinho para o perfil do user

        self.cliente = None

        if self.request.user.is_authenticated: #checando o User
            self.cliente = models.Cliente.objects.filter(cliente=self.request.user).first()

            self.contexto ={
                'userform': forms.UserForm(
                    data=self.request.POST or None,
                    usuario=self.request.user,
                    instance=self.request.user,
                    ),
                'clienteform': forms.ClienteForm(
                    data=self.request.POST or None,
                    instance=self.cliente
                    )
            }

        else:
            self.contexto ={
                'userform': forms.UserForm(data=self.request.POST or None),
                'clienteform': forms.ClienteForm(data=self.request.POST or None)
            }


        self.userform=self.contexto['userform']
        self.clienteform = self.contexto['clienteform']

        if self.request.user.is_authenticated:
            self.template_name = 'perfil/atualizar.html'


        self.renderizar = render(self.request,self.template_name,self.contexto )

    def get(self, *args, **kwargs):
        return self.renderizar


class Criar(BaseCliente):
    def post(self, *args, **kwargs):
        if not self.userform.is_valid() or not self.clienteform.is_valid():
            messages.error(
                self.request,
                'Existem erros no formulário de cadastro. Verifique se todos '
                'os campos foram preenchidos corretamente.'
            )
            return self.renderizar
        
        username = self.userform.cleaned_data.get('username')
        password = self.userform.cleaned_data.get('password')
        email = self.userform.cleaned_data.get('email')
        first_name = self.userform.cleaned_data.get('first_name')
        last_name = self.userform.cleaned_data.get('last_name')

        #user logado
        if self.request.user.is_authenticated:
            usuario = get_list_or_404(User, username=self.request.user.username)
            usuario.username = username

            if password:
                usuario.set_password(password)
            
            usuario.email =email
            usuario.first_name = first_name
            usuario.last_name = last_name
            usuario.save()

            if not self.cliente:
                self.clienteform.cleaned_data['usuario'] = usuario
                cliente = models.Cliente(**self.clienteform.cleaned_data)
                cliente.save()
            else:
                cliente = self.clienteform.save(commit=False)
                cliente.usuario= usuario
                cliente.save()


         

        #user não logado (novo)
        else:
            usuario = self.userform.save(commit=False)
            usuario.set_password(password)
            usuario.save()

            cliente = self.clienteform.save(commit=False)
            cliente.cliente= usuario
            cliente.save()

        if password:
            autentica = authenticate(self.request, username=usuario, password=password)
        
        if autentica:
            login(self.request, user=usuario)



        self.request.session['carrinho'] = self.carrinho
        self.request.session.save()

        messages.success(
            self.request,
            'Seu cadastro foi criado ou atualizado com sucesso.'
        )
        messages.success(
            self.request,
            'Você fez login e pode concluir sua compra.'
        )

        return redirect('cliente:criar')
        return self.renderizar



class Atualizar(View):
    def get(self, *args, **kwargs):
        return HttpResponse ('ATUALIZAR')


class Login(View):
    def post(self, *args, **kwargs):
        username = self.request.POST.get('username')
        password = self.request.POST.get('password')
        
        if not username or not password:
            messages.erro(
            self.request,
            'Usuario ou senha invalidos.'
            )
            return redirect('cliente:criar')
        usuario = authenticate (self.request, username=username, password=password)

        if not usuario:
            messages.erro(
            self.request,
            'Usuario ou senha invalidos.'
            )
            return redirect('cliente:criar')
        
        
        login(self.request, user=usuario)
        messages.success(
        self.request,
        'Login realizado com sucesso'
        )
        return redirect ('produto:carrinho')



class Logout(View):
    def get(self, *args, **kwargs):
        carrinho = copy.deepcopy(self.request.session.get('carrinho'))

        logout(self.request)

        self.request.session['carrinho'] = carrinho
        self.request.session.save()

        return redirect('produto:lista')

Projeto_final/pedido/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views   import View
from django.http import HttpResponse
from django.contrib import messages


class Pagar(View):
     template_name = 'pedido/pagar.html'


     def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            pass

        contexto = {

        }


        return render(self.request, self.template_name, contexto)


class SalvarPedido(View):
    def get(self, *args, **kwargs):
        return HttpResponse ('FECHAR PEDIDO')


class Detalhe(View):
    def get(self, *args, **kwargs):
        return HttpResponse ('DETALHE')

Projeto_final/produto/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404 
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from . import models
from produto.formulario import ProdutoForm, VariacaoForm
from produto.models import Produto, Variacao
from pprint import pprint
from cliente.models import Cliente



class ListaProdutos(ListView):
    model = models.Produto
    template_name = 'produto/lista.html'
    context_object_name='produtos'
    paginate_by = 8

    
    


class DetalheProdutos(DetailView):
    model = models.Produto
    template_name = 'produto/detalhe.html'
    context_object_name='produto'
    slug_url_kwarg = 'slug'


class AdicionarAoCarrinho(View):
    def get(self, *args, **kwargs):


        http_referer =self.request.META.get('HTTP_REFERER', reverse ('produto:lista'))
        prod_id = self.request.GET.get('vid')

        if not prod_id:
            messages.error(
            self.request,
            'Produto Não Existe'
            )
            return redirect(http_referer)
        
        prod= get_object_or_404(models.Variacao, id=prod_id)
        prod_estoque = prod.estoque
        produto = prod.produto

        produto_id = produto.id
        produto_nome = produto.nome
        prod_nome = prod.nome or ''
        preco_unitario = prod.preco
        preco_unitario_promocional = prod.preco_promocional
        quantidade = 1
        slug = produto.slug
        imagem = produto.imagem

        if imagem:
            imagem = imagem.name
        else:
            imagem = ''


        if prod.estoque <1:
            messages.error(
                self.request,
                "Estoque Insuficiente"
            )
            return redirect(http_referer)
       
        if not self.request.session.get('carrinho'):
            self.request.session["carrinho"] = {}
            self.request.session.save()
        
        carrinho = self.request.session['carrinho']


        if prod_id in carrinho:
            
            quantidade_carrinho = carrinho[prod_id]['quantidade']
            quantidade_carrinho +=  1
            

            

            if prod_estoque < quantidade_carrinho:
                quantidade_carrinho = prod_estoque
                messages.warning(
                self.request,
                f"Estoque Insuficiente pra {quantidade_carrinho}x  no "
                f'produto "{produto_nome}" .Adicionamos {prod_estoque}x ' 
                f' no seu carrinho '
            )
            

            carrinho[prod_id]['quantidade'] = quantidade_carrinho
            carrinho[prod_id] ['preco_quantitativo'] = preco_unitario * quantidade_carrinho
            carrinho[prod_id] ['preco_quantitativo_promocional'] = preco_unitario_promocional *  quantidade_carrinho
            

        else:
            carrinho[prod_id]={
                'produto_id'   : produto_id,
                'produto_nome' : produto_nome,
                'prod_nome' : prod_nome, 
                'prod_id' : prod_id,
                'preco_unitario' : preco_unitario,
                'preco_unitario_promocional' : preco_unitario_promocional,
                'preco_quantitativo': preco_unitario,
                'preco_quantitativo_promocional ' : preco_unitario_promocional,
                'quantidade' : quantidade,
                'slug' : slug,
                'imagem' : imagem, }

        self.request.session.save()
        pprint(carrinho)

        messages.success(
        self.request,
        f' Produto {produto_nome} {prod_nome} adicionado com sucesso ao carrinho'
        f'  Quantidade de produto adicionado {carrinho[prod_id]["quantidade"]} x.'
        )
        return redirect(http_referer)



class RemoverDoCarrinho(View):
    def get(self, *args, **kwargs):

        http_referer =self.request.META.get('HTTP_REFERER', reverse ('produto:lista'))
        prod_id = self.request.GET.get('vid')


        if not prod_id:
            return redirect(http_referer)
        if not self.request.session.get('carrinho'):
            return redirect(http_referer)

        if  prod_id not in self.request.session['carrinho']:
            return redirect(http_referer)
        
        carrinho = self.request.session['carrinho'][prod_id]

        messages.success(
            self.request,
            f'Produto {carrinho["produto_nome"]} {carrinho["prod_nome"]}'
            f'removido do seu carrinho.'

        )

        del self.request.session['carrinho'][prod_id]
        self.request.session.save()
        return redirect(http_referer)


class Carrinho(View):
    def get(self, *args, **kwargs):
        contexto = {
            'carrinho': self.request.session.get('carrinho',{})
        }
        return render(self.request, 'produto/carrinho.html', contexto)

def cadastro(request):
   operador=request.user
   print ("#####",operador)
   data = {}
   #base = {}
   data['db'] = Produto.objects.all()
   #base['db'] = Variacao.objects.all()    
   return render (request, "produto/homecadastro.html", data )

def estoque(request,pk):
   base={}
   base['db'] = Variacao.objects.get(produto=pk)
   base['estoque'] = VariacaoForm(instance=base['db'])  
   return render (request, "produto/formulario.html", base)

def adicionarproduto(request):
   data={}
   data['formulario'] = ProdutoForm()
   return render (request, "produto/formulario.html",data)


def conexao(request):
   if request.method == 'POST':
    produto = ProdutoForm(request.POST,request.FILES or None)
    estoque = VariacaoForm(request.POST,request.FILES or None)
    if produto.is_valid():        
        produto.save()
        return redirect ('produto:cadastro')
    if  estoque.is_valid():         
            estoque.save()
            return redirect ('produto:cadastro') 
    else:
        return HttpResponse ('ERRO DE CORXÃO')


def detalheproduto(request, pk):
   data={}
   data['db'] = Produto.objects.get(pk=pk)
   return render (request, 'produto/detalheproduto.html', data)

def edit(request, pk):
   data={}
   base={}
   data['db'] = Produto.objects.get(pk=pk)
   base['db'] = Variacao.objects.get(produto=pk)
   data['formulario'] = ProdutoForm(instance=data['db'])
   base['estoque'] = VariacaoForm(instance=base['db']) 
   return render (request, "produto/formulario.html",  data|base )

def update(request, pk):
    data={}
    base={}
    data['db'] = Produto.objects.get(pk=pk)  
    base['db'] = Variacao.objects.get(produto=pk)    
    if request.method == 'POST':
        produto = ProdutoForm(request.POST,request.FILES or None, instance=data['db'])
        estoque = VariacaoForm(request.POST,request.FILES or None, instance=base['db'])
        if produto.is_valid():          
            produto.save()
            return redirect ('produto:cadastro')
        if  estoque.is_valid():             
                estoque.save()
                return redirect ('produto:cadastro')   
        else:
            return HttpResponse ('ERRO DE CORXÃO')

def delete(requeste, pk):
    db = Produto.objects.get(pk=pk)
    db.delete()
    return redirect ('produto:cadastro')



class ResumoDaCompra(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('cliente:criar')

        cliente = Cliente.objects.filter(cliente=self.request.user).exists()

        if not cliente:
            messages.error(
                self.request,
                'Usuário sem perfil.'
            )
            return redirect('cliente:criar')

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Carrinho vazio.'
            )
            return redirect('produto:lista')

        contexto = {
            'usuario': self.request.user,
            'carrinho': self.request.session['carrinho'],
        }

        return render(self.request, 'produto/resumodacompra.html', contexto)

Projeto_final/templates/parciais/_carrinho.html
{% load static %}
{% load grfilters %}

<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>V.</th>
            <th>QTD.</th>
            <th>Total</th>
        </tr>

        {% for linha in carrinho.values %}
        <tr>
            <td class="d-none d-lg-block">
                <img class="cart-img" src="{%get_media_prefix%}{{linha.imagem}}">
            </td>
            <td><a href="{% url 'produto:detalhe' linha.slug %}">
                {{linha.produto_nome}}</a>

                <a class="ml-3" href="{% url 'produto:removerdocarrinho'%}?vid={{linha.prod_id}}">

                    <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                </a>
            </td>
            <td>{{linha.prod_nome}}</td>
            <td>
                {{linha.quantidade}} x  
                {% if linha.preco_unitario_promocional %}
                {{ linha.preco_unitario_promocional|formatar_preco}}
                {%else%}
                {{linha.preco_unitario|formatar_preco}}
                {%endif%}
            
            
            </td>

            {% if linha.preco_quantitativo_promocional%}
            <td>{{ linha.preco_quantitativo_promocional|formatar_preco}}</td>
            {% else %}
            <td>{{ linha.preco_quantitativo}}</td>
            {%endif%}

        </tr>

        {% endfor %}
    </table>
</div>

Projeto_final/templates/parciais/_footer.html
{% load static %}

<footer class="container-fluid bg-primary-1">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">Projeto Final</span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1">E-commerce</span>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js' %} "></script>
<script src="{% static 'assets/bootstrap/js/alerta.js' %} "></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script defer src="{% static 'assets/font-awesome/js/all.js' %}"></script>
<script src="{% static 'assets/custom/js/scripts.js' %}"></script>

Projeto_final/templates/parciais/_head.html
{% load static %}


<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css' %}">

Projeto_final/templates/parciais/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

Projeto_final/templates/parciais/_nav.html
{% load grfilters %}
{% load static %}


<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'produto:lista' %}">Mario Word !</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
<style>
    body {
        background-image: linear-gradient(rgb(250, 243, 243), rgba(241, 241, 238, 0.897)),
                  url("media/produto_imagens/2023/10/nintendo.jpg");
      
        background-position: center center ;
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
       
    }

</style>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'produto:lista' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_staff %}
                <li class="nav-item active">
                    <a class="nav-link" href=" admin/ ">Admin</a>
                </li></a>
                </li>
                    <a class="nav-link" href="{% url 'produto:cadastro' %}">Produto</a>
                 </li>
            {% endif %}

            {%if user.is_authenticated %}    
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Conta
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'cliente:criar' %}">Atualizar Dados</a>
                        <a class="dropdown-item" href="{% url 'cliente:logout' %}">Sair</a>

                    </div> 
                </li>
            {%endif%}

            
            
                <li class="nav-item active">

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'cliente:criar' %}">Entrar</a>
            </li>
            

            {% if request.session.carrinho %}
            <li class="nav-item">
                <a class="nav-link nav-cart-link active" href="{% url  'produto:carrinho' %}">
                    <span class="nav-cart-text mr-1">
                        Carrinho
                    </span>
                    <span class="nav-cart-count mr-1">
                        <strong>{{ request.session.carrinho|cart_totalqtd}} x</strong>
                    </span>
                    

                    <span class="nav-cart-icon mr-2">
                        <i class="fas fa-shopping-cart"></i>
                    </span>

                </a>
            </li>
            {%endif%}

        </ul>
        <form mothod="get">
            <input class="form-control mr-sm-2" type="text" name="Search" id="Search" placeholder="Buscar">
            <!--<button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>-->
        </form>
    </div>

    
</nav>

Projeto_final/templates/parciais/_pagination.html
{% if is_paginated %}
<div class="pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}
        <li class="page-item active">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% elif num > page_obj.number|add:'-4' and num < page_obj.number|add:'4' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endif %}