Novo-projeto/banalco/banalco/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Projeto_final/cliente/urls.py
from django.urls import path
from . import views

app_name="cliente"

urlpatterns =[
    path('', views.Criar.as_view(), name='criar'),
    path('atualizar/', views.Atualizar.as_view(), name='atualizar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),

    
]

Projeto_final/lojinha/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('produto.urls')),
    path('cliente/', include('cliente.urls')),
    path('pedido/', include('pedido.urls')),
    path('admin/', admin.site.urls),
   
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#TODO: remover debug toolbar
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ]+ urlpatterns

Projeto_final/pedido/urls.py
from django.urls import path
from . import views

app_name ='pedido'

urlpatterns =[
    path('', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('detalhe/', views.Detalhe.as_view(), name='detalhe'),   

    
]

Projeto_final/produto/urls.py
from django.urls import path
from . import views
from produto.views import cadastro, adicionarproduto, conexao, detalheproduto, edit, update, delete, estoque
from django.conf import settings
from django.conf.urls.static import static


app_name= 'produto'

urlpatterns =[
    path('', views.ListaProdutos.as_view(), name='lista'),
    path('<slug>', views.DetalheProdutos.as_view(), name='detalhe'),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(), name='adicionaraocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(), name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name='resumodacompra'),
    path('cadastro/', cadastro,name='cadastro'),
    path('adicionarproduto/', adicionarproduto, name='adicionarproduto'),
    path('detalheproduto/<int:pk>/',detalheproduto,name='detalheproduto'),
    path('conexao/', conexao,name='conexao'),
    path('estoque/<int:pk>/', estoque,name='estoque'),
    path('edit/<int:pk>/',edit,name='edit'),
    path('update/<int:pk>/',update,name='update'),
    path('delete/<int:pk>/',delete,name='delete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Senha/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

Projeto_final/produto/models.py
from django.db import models
import os    
from PIL import Image
from django.conf import settings
from django.utils.text import slugify
from utils import utils


class Produto(models.Model):
    nome = models.CharField(max_length=256)
    descricao_curta = models.TextField(max_length=256)
    desricao_longa = models.TextField()
    imagem  = models.ImageField(upload_to='produto_imagens/%Y/%m/')
    slug = models.SlugField(unique=True, blank=True, null=True)
    preco_marketing = models.FloatField(verbose_name='Preço')
    preco_marketing_promocional= models.FloatField(default=0, verbose_name='Preço Promo.')
    tipo  = models.CharField(
        default='V', 
        max_length=1,
        choices=(
            ('V', 'Variação'),
            ('S', 'Simples'),
        ) 
    )

    def get_preco_formatado(self):
        return utils.formatar_preco(self.preco_marketing)
    get_preco_formatado.short_description = "Preço"

    def get_preco_promo_formatado(self):
        return utils.formatar_preco(self.preco_marketing_promocional)
    get_preco_promo_formatado.short_description = "Preço Promocional"



    #configuração da imagem 
    @staticmethod
    def resize_image(img, new_width=800):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            print('largura original menor que nova largura')
            img_pil.close()
            return
        
        new_height = round((new_width *original_height) /original_width)
        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)
        new_img.save(
            img_full_path,
            optimize=True,
            quality=50
        )

        print('imagem redimencionada')       


    def save(self, *args, **kwargs):
        if  not self.slug:
            slug = f'{slugify(self.nome)}'
            self.slug = slug

        super().save(*args, **kwargs)

        max_image_size = 800

        if self.imagem:
            self.resize_image(self.imagem, max_image_size)

    #Nome do produto no adm 
    def __str__(self):
        return self.nome 

class Variacao(models.Model):
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    nome = models.CharField(max_length=256, blank=True, null=True)
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    estoque = models.IntegerField(default=1)

    #Nome da variação
    def __str__(self):
        return self.nome or self.produto.nome
    
    class Meta:
        verbose_name = "Variação"
        verbose_name_plural = "Variações"

Projeto_final/produto/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404 
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.http import HttpResponse
from django.contrib import messages
from . import models
from produto.formulario import ProdutoForm, VariacaoForm
from produto.models import Produto, Variacao
from pprint import pprint
from cliente.models import Cliente



class ListaProdutos(ListView):
    model = models.Produto
    template_name = 'produto/lista.html'
    context_object_name='produtos'
    paginate_by = 8

    
    


class DetalheProdutos(DetailView):
    model = models.Produto
    template_name = 'produto/detalhe.html'
    context_object_name='produto'
    slug_url_kwarg = 'slug'


class AdicionarAoCarrinho(View):
    def get(self, *args, **kwargs):


        http_referer =self.request.META.get('HTTP_REFERER', reverse ('produto:lista'))
        prod_id = self.request.GET.get('vid')

        if not prod_id:
            messages.error(
            self.request,
            'Produto Não Existe'
            )
            return redirect(http_referer)
        
        prod= get_object_or_404(models.Variacao, id=prod_id)
        prod_estoque = prod.estoque
        produto = prod.produto

        produto_id = produto.id
        produto_nome = produto.nome
        prod_nome = prod.nome or ''
        preco_unitario = prod.preco
        preco_unitario_promocional = prod.preco_promocional
        quantidade = 1
        slug = produto.slug
        imagem = produto.imagem

        if imagem:
            imagem = imagem.name
        else:
            imagem = ''


        if prod.estoque <1:
            messages.error(
                self.request,
                "Estoque Insuficiente"
            )
            return redirect(http_referer)
       
        if not self.request.session.get('carrinho'):
            self.request.session["carrinho"] = {}
            self.request.session.save()
        
        carrinho = self.request.session['carrinho']


        if prod_id in carrinho:
            
            quantidade_carrinho = carrinho[prod_id]['quantidade']
            quantidade_carrinho +=  1
            

            

            if prod_estoque < quantidade_carrinho:
                quantidade_carrinho = prod_estoque
                messages.warning(
                self.request,
                f"Estoque Insuficiente pra {quantidade_carrinho}x  no "
                f'produto "{produto_nome}" .Adicionamos {prod_estoque}x ' 
                f' no seu carrinho '
            )
            

            carrinho[prod_id]['quantidade'] = quantidade_carrinho
            carrinho[prod_id] ['preco_quantitativo'] = preco_unitario * quantidade_carrinho
            carrinho[prod_id] ['preco_quantitativo_promocional'] = preco_unitario_promocional *  quantidade_carrinho
            

        else:
            carrinho[prod_id]={
                'produto_id'   : produto_id,
                'produto_nome' : produto_nome,
                'prod_nome' : prod_nome, 
                'prod_id' : prod_id,
                'preco_unitario' : preco_unitario,
                'preco_unitario_promocional' : preco_unitario_promocional,
                'preco_quantitativo': preco_unitario,
                'preco_quantitativo_promocional ' : preco_unitario_promocional,
                'quantidade' : quantidade,
                'slug' : slug,
                'imagem' : imagem, }

        self.request.session.save()
        pprint(carrinho)

        messages.success(
        self.request,
        f' Produto {produto_nome} {prod_nome} adicionado com sucesso ao carrinho'
        f'  Quantidade de produto adicionado {carrinho[prod_id]["quantidade"]} x.'
        )
        return redirect(http_referer)



class RemoverDoCarrinho(View):
    def get(self, *args, **kwargs):

        http_referer =self.request.META.get('HTTP_REFERER', reverse ('produto:lista'))
        prod_id = self.request.GET.get('vid')


        if not prod_id:
            return redirect(http_referer)
        if not self.request.session.get('carrinho'):
            return redirect(http_referer)

        if  prod_id not in self.request.session['carrinho']:
            return redirect(http_referer)
        
        carrinho = self.request.session['carrinho'][prod_id]

        messages.success(
            self.request,
            f'Produto {carrinho["produto_nome"]} {carrinho["prod_nome"]}'
            f'removido do seu carrinho.'

        )

        del self.request.session['carrinho'][prod_id]
        self.request.session.save()
        return redirect(http_referer)


class Carrinho(View):
    def get(self, *args, **kwargs):
        contexto = {
            'carrinho': self.request.session.get('carrinho',{})
        }
        return render(self.request, 'produto/carrinho.html', contexto)

def cadastro(request):
   operador=request.user
   print ("#####",operador)
   data = {}
   #base = {}
   data['db'] = Produto.objects.all()
   #base['db'] = Variacao.objects.all()    
   return render (request, "produto/homecadastro.html", data )

def estoque(request,pk):
   base={}
   base['db'] = Variacao.objects.get(produto=pk)
   base['estoque'] = VariacaoForm(instance=base['db'])  
   return render (request, "produto/formulario.html", base)

def adicionarproduto(request):
   data={}
   data['formulario'] = ProdutoForm()
   return render (request, "produto/formulario.html",data)


def conexao(request):
   if request.method == 'POST':
    produto = ProdutoForm(request.POST,request.FILES or None)
    estoque = VariacaoForm(request.POST,request.FILES or None)
    if produto.is_valid():        
        produto.save()
        return redirect ('produto:cadastro')
    if  estoque.is_valid():         
            estoque.save()
            return redirect ('produto:cadastro') 
    else:
        return HttpResponse ('ERRO DE CORXÃO')


def detalheproduto(request, pk):
   data={}
   data['db'] = Produto.objects.get(pk=pk)
   return render (request, 'produto/detalheproduto.html', data)

def edit(request, pk):
   data={}
   base={}
   data['db'] = Produto.objects.get(pk=pk)
   base['db'] = Variacao.objects.get(produto=pk)
   data['formulario'] = ProdutoForm(instance=data['db'])
   base['estoque'] = VariacaoForm(instance=base['db']) 
   return render (request, "produto/formulario.html",  data|base )

def update(request, pk):
    data={}
    base={}
    data['db'] = Produto.objects.get(pk=pk)  
    base['db'] = Variacao.objects.get(produto=pk)    
    if request.method == 'POST':
        produto = ProdutoForm(request.POST,request.FILES or None, instance=data['db'])
        estoque = VariacaoForm(request.POST,request.FILES or None, instance=base['db'])
        if produto.is_valid():          
            produto.save()
            return redirect ('produto:cadastro')
        if  estoque.is_valid():             
                estoque.save()
                return redirect ('produto:cadastro')   
        else:
            return HttpResponse ('ERRO DE CORXÃO')

def delete(requeste, pk):
    db = Produto.objects.get(pk=pk)
    db.delete()
    return redirect ('produto:cadastro')



class ResumoDaCompra(View):
    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('cliente:criar')

        cliente = Cliente.objects.filter(cliente=self.request.user).exists()

        if not cliente:
            messages.error(
                self.request,
                'Usuário sem perfil.'
            )
            return redirect('cliente:criar')

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Carrinho vazio.'
            )
            return redirect('produto:lista')

        contexto = {
            'usuario': self.request.user,
            'carrinho': self.request.session['carrinho'],
        }

        return render(self.request, 'produto/resumodacompra.html', contexto)

Projeto_final/produto/templates/produto/carrinho.html
{% extends 'base.html' %}
{% load grfilters %}



{% block conteudo %}

{% if carrinho %}

<div class="row mt-3">
    <div class="col">
        <h3>Carrinho de compras</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        {%include 'parciais/_carrinho.html'%}
    </div>
</div>



<div class="row mt-3">
    <div class="col-lg">
        <p class='lead'>Total no carrinho</p>

        <div class='table-responsive'>
            <table class="table">
                <tr>
                    <td class="font-weight-bold">Total</td>
                    <td>{{carrinho|cart_totals|formatar_preco}}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-lg mt-auto">

        {%if request.user.is_authenticated%}
        <a class="btn btn-lg btn-block btn-primary" href="{%url 'produto:resumodacompra'%}">
            Finalizar a compra
        </a>
        {%else%}
        <a class="btn btn-lg btn-block btn-primary" href="{%url 'cliente:criar'%}">
            Logar
        </a>


        {%endif%}
    </div>
</div>

{% else %}

<div class="row mt-3">
    <div class="col">
        <h3>Carrinho Vazio</h3>
        <p class="lead">Não há produtos no seu carrinho</p>
    </div>
</div>


{% endif %}

{% endblock%}

Projeto_final/produto/templates/produto/detalhe.html
{% extends 'base.html' %}
{% load grfilters %}
{% block conteudo %}
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg">
                <div class="row no-gutters">
                    <div class="col-lg-12">
                        {% if produto.imagem %}
                            <img class="img-fluid" src="{{produto.imagem.url}}">
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-lg">
                <div class="mt-4 mt-lg-0">
                    <h1 class="h2">{{produto.nome}}</h1>
                    <p class="lead">{{produto.descricao_curta}}</p>
                    <p class="lead">
                        {% if produto.preco_marketing_promocional %}
                            <span id="variation-preco-promocional" class="lead product-price">{{ produto.preco_marketing_promocional|formatar_preco}}</span>
                            <span id="variation-preco"class="lead product-old-price text-muted">{{ produto.preco_marketing|formatar_preco}}
                            </span>
                        {% else %}
                            <span id="variation-preco" class="lead product-price">{{ produto.preco_marketing|formatar_preco}}</span>
                        {% endif %}    
                   
                            
                        <form action="{% url 'produto:adicionaraocarrinho' %}" id="form-add-to-cart" name="vid" >
                            <div class="form-group">
                                <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                                {% for variacao in produto.variacao_set.all %}

                                   {% if variacao.preco_promocional %}
                                        <option data-preco="{{variacao.preco|formatar_preco}}"
                                            data-preco-promocional="{{variacao.preco_promocional|formatar_preco }}"
                                            value="{{variacao.id }}">
                                            {% if variacao.nome %}
                                            {{variacao.nome }}
                                            {% else %}
                                            {{variacao }}
                                            {% endif %}
                                        </option>
                                    {% else %}
                                        <option data-preco="{{variacao.preco|formatar_preco }}" value="{{variacao.id }}">
                                            {% if variacao.nome %}
                                            {{ variacao.nome }}
                                            {% else %}
                                            {{ variacao }}
                                            {% endif %}
                                        </option>
                                    {% endif %}
                     
                                {% endfor %}
                                        
                                </select>
                                
                            
                            </div>
                    
                        <div class="text-left">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Adicionar ao carrinho
                            </button>
                        </div>

                    </form>
                

                </div>
            </div>
        </div>


 

    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="mt-5 mb-5">
            <h2 class="text-center">{{produto.nome}}</h2>
                {{produto.desricao_longa}}
        </div>
    </div>
</div>

{% endblock %}

Projeto_final/produto/templates/produto/detalheproduto.html
{% extends 'base.html' %}
{% load grfilters %}
{% load static %}


{% block conteudo %}

    
    <div class="=col-8 m-auto pt-2 pb-2 text-center ">
        <h1> Detalhes </h1>
    </div>

    <div class="=col-8 m-auto pt-2 pb-2 text-center">
        <a href="{% url 'produto:cadastro' %}" class="btn btn-info">Voltar</a>
    </div>

    <div class="=col-8 m-auto pt-2 pb-2 text-center">
      <strong>Produto: </strong> {{db.nome}} <br>
      <strong>Valor: </strong> {{db.preco_marketing }} <br>
      <strong>Sobre: </strong> {{db.descricao_curta }} <br>
      <strong>Quantidade: </strong> {{db.estoque}} <br>
    </div>



{% endblock%}

Projeto_final/produto/templates/produto/formulario.html
{% extends 'base.html' %}
{% load grfilters %}
{% load static %}


{% block conteudo %}
    
    <div class="=col-8 m-auto pt-2 pb-2 text-center ">
        <h1> Cadastro </h1>
    </div>

    <div class="=col-8 m-auto pt-2 pb-2 text-center">
        <a href="{% url 'produto:cadastro' %}" class="btn btn-info">Voltar</a>
    </div>

    <div class="=col-8 m-auto pt-2 pb-2 text-center">
      <div id="result"></div>
      <form  name="form" id="form" action="{% if db%}/update/{{db.id}}/{%else%}/conexao/{%endif%}" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{formulario.as_p}}
          {{estoque.as_p}}

          
          
               
       <input type="submit" class="btn btn-success" value="Salvar"> <!-- <a href="/estoque/{{dbs.id}}" class="btn btn-warning"> Estoque</a> -->
      </form>
      
    
    </div>

{%endblock%}

Projeto_final/produto/templates/produto/homecadastro.html
{% extends 'base.html' %}
{% load grfilters %}
{% load static %}


{% block conteudo %}
    
    <div class="=col-8 m-auto pt-2 pb-2 text-center ">
        <h1> Produtos {{user}} </h1>
    </div>

    <div class="=col-8 m-auto pt-2 pb-2 text-center">
        <a href="{% url 'produto:adicionarproduto'  %}"class="btn btn-success"> Adicionar</a>
    </div>

    <div class="=col-8 m-auto pt-2 pb-2 text-center">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">ID</th>
                <th scope="col">Produto</th>
                <th scope="col">Valor</th>
                <th scope="col">Valor de promoção</th>
                <th scope="col">Quantidade</th>
                <!--<th scope="col">Ações</th>-->
              </tr>
            </thead>
            <tbody>
              {% for dbs in db%}
                <tr>
                  <th scope="row">{{dbs.id}}</th>
                  <td>{{dbs.nome}}</td>
                  <td>{{dbs.preco_marketing}}</td>
                  <td>{{dbs.preco_marketing_promocional}}</td>
                 <!-- <td>{{dbs.estoque}}</td>-->
                  
                  
                  <td>
                    <a href="/detalheproduto/{{dbs.id}}/" class="btn btn-dark"> Detalhes</a>
                    <a href="/edit/{{dbs.id}}/" class="btn btn-primary"> Editar</a>
                    <a href="/delete/{{dbs.id}}/" class="btn btn-danger btnDel"> Deletar</a>
                   <a href="/estoque/{{dbs.id}}/" class="btn btn-warning"> Estoque</a>
                    </td>
                </tr>
              {% endfor %}
          </table>
    </div>
    
{% endblock%}

Projeto_final/produto/templates/produto/lista.html
{% extends 'base.html' %}
{% load grfilters %}
{% block conteudo %}



<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="media/produto_imagens/2023/10/zelda.webp" alt="Zelda">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="media/produto_imagens/2023/10/mario.jpg" alt="Mario">
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="media/produto_imagens/2023/11/DK.jpg" alt="Third slide">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

<br>
<br>

<div class="row">
    <div class="col-lg-12">
        <div class="card-columns">

            {% for produto in produtos%}
            <div class="card">

                {% if produto.imagem %}
                    <a href="{{produto.slug}}">
                        <center><img class="card-img-top img-capajogo " src="{{produto.imagem.url}}" alt="{{produto.nome}}"></center>
                    </a>    
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{produto.nome}}</h5>
                    <p class="card-text">{{produto.descricao_curta}}</p>
                    <div class="container product-price-block text-center">
                        {% if produto.preco_marketing_promocional %}
                            <span class="product-price">
                                {{ produto.preco_marketing_promocional|formatar_preco}}
                            </span>

                            <span class="product-old-price text-muted">
                                {{ produto.preco_marketing|formatar_preco }}
                            </span>
                        {% else %}   
                            <span class="product-price">
                                {{ produto.preco_marketing|formatar_preco}}
                            </span>
                        {% endif %}

                    </div>
                </div>
                <div class="card-footer bg-transparent border-top-light-custom text-center">
                  <a href="{{produto.slug}}" class="btn btn-primary btn-sm m-1 btn-block"> 
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Comprar
                    </a>
                </div>
            </div>


            
            {% endfor %}   


        </div>
    </div>
</div>
<div>
    <div class="'row mt-3">
        <div class="col">
            {% include 'parciais/_pagination.html'%}
        </div>
    </div>
</div>

{% endblock %}

Projeto_final/produto/templates/produto/resumodacompra.html
{% extends 'base.html' %}
{% load grfilters %}




{% block conteudo %}

<div class="row mb-5">
    <div class="col-lg">
        <h2>Resumo da sua compra</h2>

        <p class="lead">Dados do usuário</p>
        <p>Caso precise editar, <a href="{% url 'cliente:criar' %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Nome:</dt>
            <dd class="col-lg-4">{{ usuario.first_name }}</dd>
            <dt class="col-lg-2">Sobrenome:</dt>
            <dd class="col-lg-4">{{ usuario.last_name }}</dd>

            <dt class="col-lg-2">Idade:</dt>
            <dd class="col-lg-4">{{ usuario.cliente.idade }}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{ usuario.cliente.data_nascimento }}</dd>

            <dt class="col-lg-2">CPF:</dt>
            <dd class="col-lg-4">{{ usuario.cliente.cpf }}</dd>
            <dt class="col-lg-2">E-mail:</dt>
            <dd class="col-lg-4">{{ usuario.email }}</dd>
        </dl>

        <p class="lead">Dados de endereço</p>
        <p>Caso precise editar, <a href="{% url 'cliente:criar' %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Endereço:</dt>
            <dd class="col-lg-4">{{ usuario.cliente.endereco }}</dd>
            <dt class="col-lg-2">Número:</dt>
            <dd class="col-lg-4">{{ usuario.cliente.numero }}</dd>

            <dt class="col-lg-2">Complemento:</dt>
            <dd class="col-lg-4">{{ usuario.cliente.complemento }}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{ usuario.cliente.bairro }}</dd>

            <dt class="col-lg-2">Cidade:</dt>
            <dd class="col-lg-4">{{ usuario.cliente.cidade }}</dd>
            <dt class="col-lg-2">Estado:</dt>
            <dd class="col-lg-4">{{ usuario.cliente.estado }}</dd>

            <dt class="col-lg-2">CEP:</dt>
            <dd class="col-lg-4">{{ usuario.cliente.cep }}</dd>
        </dl>
    </div>
</div>



<div class="row mt-3">
    <div class="col">
        <h3>Resumo do carrinho</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        {% include 'parciais/_carrinho.html' %}
    </div>

</div>
<div class="row mt-3">
    <div class="col">
        <p class="lead text-center"><span class="font-weight-bold">Total do carrinho:</span>
            {{ carrinho|cart_totals|formatar_preco }}</p>
    </div>
</div>

<div class="row">
    <div class="col">
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'pedido:salvarpedido' %}">
            Realizar pedido e pagar
        </a>
    </div>
</div>


{% endblock %}